server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beyondwords_user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: madhumitha_15
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: madhumithagopal82@gmail.com
    password: pxjpxjjcivhwtndn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

app:
  jwt:
    secret: beyondwords-super-secret-key-change-me
    expiration-ms: 86400000

logging:
  file:
    name: user-service-error.log
